---
apiVersion: v1
kind: Namespace
metadata:
  name: fargate
  labels:
    name: fargate
---
# namespace for logging
# https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html#fargate-logging-log-router-configuration
kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
