---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-xfs-sc
parameters:
  csi.storage.k8s.io/fstype: xfs
  iops: "4000"
  type: io2
  blockSize: "1024"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
