---
apiVersion: v1
kind: Pod
metadata:
  name: test-xfs
  namespace: ebs
spec:
  containers:
    - name: test-xfs
      image: centos
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  nodeSelector:
    eks.amazonaws.com/nodegroup: managed-nodegroup-hugepage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-xfs-claim
