apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-fluentbit-pvc
  namespace: amazon-cloudwatch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
