---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-nginx
  namespace: karpenter
  labels:
    test: OK
spec:
  selector:
    matchLabels:
      app: karpenter-nginx
  replicas: 3  # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: karpenter-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
